### ISSUE TITLE
Image overflow

### ISSUE THREAD

**Issue by melissamcewen** [KarlGoddard/colmar#4]
Yeah so the image overflow issue you experienced is really common. Like I don't know how many times I had a perfect grid layout and some designer I'm working with sends me an image that messes it up because it's the wrong size. One way to deal with this issues is containers (others include image cropping on the backend which I also use for performance reasons). Like create a nice container for the images and set it so overflow is hidden 

```css
.media-container {
  overflow: hidden;
}

.media-container img,
.media-container video {
  display: block;
  width: 100%;
}

```

![media-container](https://user-images.githubusercontent.com/1251094/37049270-014bcba6-2136-11e8-8546-b240ecb9ee87.jpg)

of course then the entire thing is too big but that can be fixed at the flexbox layout level

I'm going to attach the solution here because I think some of this is caused by not having the assets (there are mobile and desktop images for example). This solution has the assets as well as the flexbox layout.  https://s3.amazonaws.com/codecademy-content/courses/freelance-1/project-solutions/F1U8PJumpstart_solution.zip
